
//! Autogenerated weights for `pallet_metarium`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-10-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Meenakshis-MBP`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/parachain-template-node
// benchmark
// pallet
// --chain
// dev
// --wasm-execution=compiled
// --pallet
// pallet_metarium
// --extrinsic
// *
// --output
// templates/parachain/pallets/metarium/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_metarium`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_metarium::WeightInfo for WeightInfo<T> {
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:1)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn force_add_node_to_scribe_set() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3514`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(9_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:1)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn force_remove_node_from_scribe_set() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `3514`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::NodeInfoMap` (r:0 w:1)
	/// Proof: `Metarium::NodeInfoMap` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	fn node_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `3514`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::NodeInfoMap` (r:0 w:1)
	/// Proof: `Metarium::NodeInfoMap` (`max_values`: None, `max_size`: Some(1090), added: 3565, mode: `MaxEncodedLen`)
	fn force_update_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `3514`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::CustodianSetMap` (r:1 w:1)
	/// Proof: `Metarium::CustodianSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn force_add_node_to_custodian_set() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `3514`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(12_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::CustodianSetMap` (r:1 w:1)
	/// Proof: `Metarium::CustodianSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	fn force_remove_node_from_custodian_set() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `151`
		//  Estimated: `3514`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::CustodianSetMap` (r:1 w:0)
	/// Proof: `Metarium::CustodianSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::TotalChannels` (r:1 w:1)
	/// Proof: `Metarium::TotalChannels` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:0 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn channel_added() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `188`
		//  Estimated: `3514`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::CustodianSetMap` (r:1 w:0)
	/// Proof: `Metarium::CustodianSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn channel_configurator_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `352`
		//  Estimated: `3514`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(17_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn force_unarchive_channel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `277`
		//  Estimated: `3464`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3464))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::CustodianSetMap` (r:1 w:0)
	/// Proof: `Metarium::CustodianSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:0)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::ChannelTransferAccepted` (r:0 w:1)
	/// Proof: `Metarium::ChannelTransferAccepted` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	fn channel_transfer_accepted() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `352`
		//  Estimated: `3514`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::CustodianSetMap` (r:1 w:0)
	/// Proof: `Metarium::CustodianSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:0)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::ChannelTransferAccepted` (r:0 w:1)
	/// Proof: `Metarium::ChannelTransferAccepted` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	fn channel_transfer_rejected() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `386`
		//  Estimated: `3514`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(16_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::ChannelTransferAccepted` (r:1 w:1)
	/// Proof: `Metarium::ChannelTransferAccepted` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	fn channel_transferred_once() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `410`
		//  Estimated: `3538`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(22_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3538))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::ChannelTransferAccepted` (r:1 w:1)
	/// Proof: `Metarium::ChannelTransferAccepted` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	fn channel_transferred_twice() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `451`
		//  Estimated: `3538`
		// Minimum execution time: 22_000_000 picoseconds.
		Weight::from_parts(22_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3538))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn channel_archived() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `315`
		//  Estimated: `3514`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(13_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn channel_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `315`
		//  Estimated: `3514`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(13_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn channel_unpaused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `315`
		//  Estimated: `3514`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(13_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn node_added_to_channel_actant_set() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `315`
		//  Estimated: `3514`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(15_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn node_removed_from_channel_actant_set() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `347`
		//  Estimated: `3514`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::ChannelsPerListenerMap` (r:1 w:1)
	/// Proof: `Metarium::ChannelsPerListenerMap` (`max_values`: None, `max_size`: Some(524340), added: 526815, mode: `MaxEncodedLen`)
	fn node_added_to_channel_listener_set() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `315`
		//  Estimated: `527805`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(18_000_000, 0)
			.saturating_add(Weight::from_parts(0, 527805))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::ChannelsPerListenerMap` (r:1 w:1)
	/// Proof: `Metarium::ChannelsPerListenerMap` (`max_values`: None, `max_size`: Some(524340), added: 526815, mode: `MaxEncodedLen`)
	fn node_removed_from_channel_listener_set() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `347`
		//  Estimated: `527805`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(17_000_000, 0)
			.saturating_add(Weight::from_parts(0, 527805))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	fn channel_maker_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `315`
		//  Estimated: `3514`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Arikuris` (r:1 w:0)
	/// Proof: `Metarium::Arikuris` (`max_values`: None, `max_size`: Some(565), added: 3040, mode: `MaxEncodedLen`)
	fn channel_metadata_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `409`
		//  Estimated: `4030`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(17_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4030))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Arikuris` (r:1 w:0)
	/// Proof: `Metarium::Arikuris` (`max_values`: None, `max_size`: Some(565), added: 3040, mode: `MaxEncodedLen`)
	fn channel_functional_metadata_updated() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `409`
		//  Estimated: `4030`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(17_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4030))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:0)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::ChannelCustodianMetadataCommitThreads` (r:1 w:1)
	/// Proof: `Metarium::ChannelCustodianMetadataCommitThreads` (`max_values`: None, `max_size`: Some(404), added: 2879, mode: `MaxEncodedLen`)
	fn channel_custodian_metadata_commit_thread_lock_requested() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `347`
		//  Estimated: `3869`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(15_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3869))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:0)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::ChannelCustodianMetadataCommitThreads` (r:1 w:1)
	/// Proof: `Metarium::ChannelCustodianMetadataCommitThreads` (`max_values`: None, `max_size`: Some(404), added: 2879, mode: `MaxEncodedLen`)
	fn channel_custodian_metadata_commit_thread_lock_release_requested() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `440`
		//  Estimated: `3869`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(16_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3869))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::Channels` (r:1 w:0)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::ChannelCustodianMetadataCommitThreads` (r:1 w:1)
	/// Proof: `Metarium::ChannelCustodianMetadataCommitThreads` (`max_values`: None, `max_size`: Some(404), added: 2879, mode: `MaxEncodedLen`)
	fn force_release_channel_custodian_metadata_commit_thread_lock() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `402`
		//  Estimated: `3869`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3869))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Arikuris` (r:1 w:0)
	/// Proof: `Metarium::Arikuris` (`max_values`: None, `max_size`: Some(565), added: 3040, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::ChannelCustodianMetadataCommitThreads` (r:1 w:1)
	/// Proof: `Metarium::ChannelCustodianMetadataCommitThreads` (`max_values`: None, `max_size`: Some(404), added: 2879, mode: `MaxEncodedLen`)
	fn channel_custodian_metadata_updated_without_thread_lock_release() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `534`
		//  Estimated: `4030`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(22_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4030))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:1)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Arikuris` (r:1 w:0)
	/// Proof: `Metarium::Arikuris` (`max_values`: None, `max_size`: Some(565), added: 3040, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::ChannelCustodianMetadataCommitThreads` (r:1 w:1)
	/// Proof: `Metarium::ChannelCustodianMetadataCommitThreads` (`max_values`: None, `max_size`: Some(404), added: 2879, mode: `MaxEncodedLen`)
	fn channel_custodian_metadata_updated_with_thread_lock_release() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `534`
		//  Estimated: `4030`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(22_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4030))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Arikuris` (r:1 w:1)
	/// Proof: `Metarium::Arikuris` (`max_values`: None, `max_size`: Some(565), added: 3040, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:0)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::TotalArikuris` (r:1 w:1)
	/// Proof: `Metarium::TotalArikuris` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn arikuri_added() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `347`
		//  Estimated: `4030`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(18_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4030))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Metarium::ScribeSetMap` (r:1 w:0)
	/// Proof: `Metarium::ScribeSetMap` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Channels` (r:1 w:0)
	/// Proof: `Metarium::Channels` (`max_values`: None, `max_size`: Some(4294967295), added: 2474, mode: `MaxEncodedLen`)
	/// Storage: `Metarium::Arikuris` (r:1 w:1)
	/// Proof: `Metarium::Arikuris` (`max_values`: None, `max_size`: Some(565), added: 3040, mode: `MaxEncodedLen`)
	fn arikuri_deleted() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `441`
		//  Estimated: `4030`
		// Minimum execution time: 17_000_000 picoseconds.
		Weight::from_parts(18_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4030))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
